### ISSUE TITLE
Release v0.3.0

### ISSUE THREAD

**Issue by chrisheninger** [elm-street-technology/elevate-ui#39]
Possibly has some breaking changes– be aware when updating existing projects using v0.2.x

# Components:
- [x] Checkbox (:focus styles, snapshot updates, clean-up)
- [x] Radio (:focus styles, snapshot updates, clean-up)
- [x] Table component (New! Functionality, styles, demo) https://github.com/elm-street-technology/elevate-ui/issues/12
- [x] CheckboxTable component (New! Functionality, demo)
- [x] Scaffold component (New! Functionality, updates to all related components (input, textarea, etc.)) (#10)

# General:
- [x] Add `theme.typography.bodyColor` and set on `html, body` in `GlobalsAndReset`
- [x] Add `button:disabled` styles in `GlobalsAndReset`
- [x] Eject and update demo to read `elevate-ui` from itself https://github.com/elm-street-technology/elevate-ui/issues/37
- [x] Prettier updates https://github.com/elm-street-technology/elevate-ui/issues/26

# Screenshots:
#### Table
<img width="909" alt="screen shot 2018-05-22 at 12 17 58 pm" src="https://user-images.githubusercontent.com/5051745/40386046-83a78338-5dbd-11e8-8e66-97f5637f1579.png">

#### CheckboxTable
<img width="908" alt="screen shot 2018-05-22 at 9 54 15 am" src="https://user-images.githubusercontent.com/5051745/40386056-89b899ce-5dbd-11e8-9637-921ef83c31bd.png">

#### Checkbox (Before)
<img width="426" alt="screen shot 2018-05-21 at 3 27 51 pm" src="https://user-images.githubusercontent.com/5051745/40333127-b072c768-5d0b-11e8-9005-99769cc576d6.png">

#### Checkbox (Now)
<img width="427" alt="screen shot 2018-05-21 at 3 28 32 pm" src="https://user-images.githubusercontent.com/5051745/40333130-b3a9f7da-5d0b-11e8-8b4b-891e4efb888b.png">

#### Radio (Before)
<img width="377" alt="screen shot 2018-05-21 at 3 31 05 pm" src="https://user-images.githubusercontent.com/5051745/40333190-17c35950-5d0c-11e8-8705-ea0d68b4a232.png">

#### Radio (Now)
<img width="367" alt="screen shot 2018-05-21 at 3 31 19 pm" src="https://user-images.githubusercontent.com/5051745/40333195-1b707a88-5d0c-11e8-92a3-a0c479321162.png">

**Comment by chrisheninger** [comment]
Published as 0.3.0 https://www.npmjs.com/package/elevate-ui
